version: '3.7'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: host-mongo
    hostname: host-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb/
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - "8007:27017"